name: Build new files for updated versions
on:
  push:
    paths:
      - '*/version'
jobs:
  build-prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Check for new versions of images and write to output var
        run: ./build_prep.sh

  build:
    needs: build-prep
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build-prep.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:v0.9.3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - env:
          REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
          BUILD_DIR: ${{ matrix.dir }}
        run: /build_single.sh
        