name: Build new files for updated versions
on:
  push:
    paths:
      - '*/version'
jobs:
  build-prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check for new versions of images
        run: ./build.sh
        
  build:
    # TODO dynamic matrix based on image list from last job