name: Build new images for updated versions
on:
  schedule:
    - cron: '8 13 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check for new versions of images
        if: github.event_name != 'workflow_dispatch'
        run: ./update.sh

      - name: Commit new version files
        if: github.event_name != 'workflow_dispatch'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "updated versions"
          git push
      
      - id: set-matrix
        name: Check for new versions of images and write to output var
        run: ./build_prep.sh

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      matrix_dirs: ${{ steps.set-matrix.outputs.matrix_dirs }}


  build:
    needs: update
    runs-on: ubuntu-latest
    if: needs.update.outputs.matrix != '[]'
    strategy:
      matrix:
        include: ${{fromJson(needs.update.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:v0.9.3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        env:
          REPOSITORY: ${{ secrets.REPOSITORY }}
          BUILD_DIR: ${{ matrix.dir }}
          VERSION: ${{ matrix.version }}
        run: ./build_single.sh


  push-manifest:
    needs: [build, update]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{fromJson(needs.update.outputs.matrix_dirs)}}
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push manifest
        env:
          REPOSITORY: ${{ secrets.REPOSITORY }}
          BUILD_DIR: ${{ matrix.dir }}
        run: ./push_manifest.sh